---
- name: Recargar systemd y reiniciar sysmonitor
  ansible.builtin.systemd:
    daemon_reload: true
    name: sysmonitor.service
    state: restarted
    enabled: true

- name: Restaurar contextos SELinux
  ansible.builtin.command:
    cmd: restorecon -R -F {{ sysmonitor_install_dir }} {{ sysmonitor_log_dir }}
